In [2]:
import torch

张量表示一个由数值组成的数组，这个数组可能有多个维度。
具有一个轴的张量对应数学上的向量 vector； 具有两个轴的张量对应数学上的矩阵 matrix； 具有两个轴以上的张量没有特殊的数学名称。
张量中的每个值称为张量的元素 element

In [3]:
x = torch.arange(12)
print(x)
print(x.type()) # x的数据类型
print(x.shape) # x的形状
print(x.numel()) # x中元素的总数

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.LongTensor
torch.Size([12])
12


改变张量的形状而不改变元素数量和元素值，可以调用reshape函数。
通过改变张量的形状，张量的大小不会改变。

不需要通过手动指定每个维度来改变形状。如果目标形状是（高度，宽度），那么在知道宽度后，高度会被自动计算得出，不必自己做除法。
可以通过-1来调用自动计算维度的功能。

In [6]:
X = x.reshape(3,4)
print(X)

X = x.reshape(-1,4)
print(X)

X = x.reshape(3,-1)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


使用全0，全1，其他常量。

In [9]:
x = torch.zeros((2,3,4))
print(x)
y = torch.ones((2,3,4))
print(y)
z = torch.randn((2,3,4))
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[ 2.1304, -1.2695,  0.8879, -0.9276],
         [-0.6840, -0.2777,  1.4807,  0.6891],
         [ 0.7652, -0.7412,  1.6432,  0.0110]],

        [[ 0.1229,  1.0039, -0.0227,  0.4848],
         [-0.1732, -0.2292, -0.2549,  1.4869],
         [-0.0296, -0.1151, -1.3791,  1.2926]]])


运算符，按元素 elementwise运算。将标准标量运算符应用于数组的每个元素。对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每对位置对应的元素。
一元标量运算符：只接收一个输入
二元标量运算符：该函数接收两个输入，并产生一个输出。
给定同一形状的任意两个向量u和v和二元运算符f，我们可以得到向量C=F(u,v)。 具体的计算方法是Ci = f(ui,vi), Ci ui vi 分别是向量C,u,v中的元素。
在这里，我们通过将标量函数升级为按元素向量运算来生成向量值F: R, R->R

In [10]:
x = torch.Tensor([1.0,2,4,8])
y = torch.Tensor([2,2,2,2])

x+y, x-y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式可以应用更多的计算，包括像求幂的一元运算符。

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

可以将多个张量连结 concatenate在一起，端对端地叠起来形成一个更大的张量。
需要提供张量列表，并给出沿哪个轴连结。

In [15]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
print(X)

Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(Y)

torch.cat((X,Y), dim = 0), torch.cat((X,Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

逻辑运算符构建二元张量

In [16]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和，会产生一个单元素张量。

In [17]:
X.sum()

tensor(66.)

广播机制
在某些情况下，即使形状不同，仍然可以通过调用广播机制 broadcasting mechanism来执行按元素操作。
这种机制的工作方式如下：
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
2. 对生成的数组执行按元素操作

In [22]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)

c = a+b
print(c)
print(c.shape)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
torch.Size([3, 2])


索引和切片
张量中的元素可以通过索引访问。
与任何python数组一样：
第一个元素的索引是0，最后一个元素索引是-1，可以指定范围以包含第一个元素和最后一个之前的元素。

In [23]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，还可以通过指定索引来将元素写入矩阵。

In [24]:
print(X)
X[1,2] = 9

print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


如果要为多个元素赋值相同的值，只需要索引这些元素，然后为它们赋值。

In [25]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

节省内存
运行一些操作可能会导致为新结果分配内存。
例如如果用Y = X+Y, 将取消引用Y指向的向量，二十指向新分配的内存处的张量。
下面的例子中，用python的id()函数演示了这一点，它给我们提供了内存中引用对象的确切地址。

In [27]:
before = id(Y)
print(before)
Y = X+Y
id(Y) == before

3168816327152


False

这是不可取的，原因有两个：
1. 首先，我们不想总是不必要地分配内存。
2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

执行原地操作，可以使用切片表示法将操作的结果分配给先前分配的数组。

In [28]:
Z = torch.zeros_like(Y)
print(Z)
print('id(Z):', id(Z))

Z[:] = Z + Y
print(Z)
print('id(Z):', id(Z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 3168812976544
tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])
id(Z): 3168812976544


转换为其他python对象
将深度学习框架定义的张量转换为numpy张量narray很容易，反之亦然。
torch张量和numpy数组将共享它们的底层内存，就地操作更改一张张量也会同时更改另一个张量。

In [29]:
A = X.numpy()
B = torch.Tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为python标量，我们可以调用item函数或者python的内置函数

In [31]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

数据预处理
举一个例子，首先创建一个人工数据集。

In [32]:
import os
os.makedirs(os.path.join('.','data'), exist_ok = True)
data_file = os.path.join('.','data', 'house_tiny.csv')

with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [43]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


处理缺失值
典型的方法包括插值法和删除法。
插值法用一个替代值弥补缺失值。
删除法则直接忽略缺失值。

通过位置索引iloc，我们将data分成inputs和outputs，其中前者为data的前两列，而后者为data的最后一列。
对于inputs中缺少的数值，我们用同一列的均值替换"NaN"项。

In [44]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
print(inputs, outputs)

print(inputs[inputs.select_dtypes(include = ['number']).columns])
inputs[inputs.select_dtypes(include = ['number']).columns] = inputs.select_dtypes(include = ['number']).fillna(inputs.select_dtypes(include = ['number']).mean())
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN 0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64
   NumRooms
0       NaN
1       2.0
2       4.0
3       NaN
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于inputs中的类别或离散值，我们将"NaN“视为一个类别。

In [47]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

inputs = inputs.astype(int)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True
   NumRooms  Alley_Pave  Alley_nan
0         3           1          0
1         2           0          1
2         4           0          1
3         3           0          1


转换为张量格式
将数值类型转换为张量格式。

In [48]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))

X, y


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

练习： 
1. 创建包含更多行和列的原始数据集
2. 删除缺失值最多的列
3. 将预处理后的数据集转换为张量格式

In [52]:
os.makedirs(os.path.join('.','data'), exist_ok = True)
data_file = os.path.join('.','data', 'house_tiny2.csv')

with open(data_file, 'w') as f:
    f.write('NumRooms,Size,Alley,Price\n')  # 列名
    f.write('NA,100,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,120,NA,106000\n')
    f.write('4,130,NA,178100\n')
    f.write('NA,NA,NA,140000\n')

print(data_file)
print(f)

data = pd.read_csv(data_file)
print(data)

.\data\house_tiny2.csv
<_io.TextIOWrapper name='.\\data\\house_tiny2.csv' mode='w' encoding='UTF-8'>
   NumRooms   Size Alley   Price
0       NaN  100.0  Pave  127500
1       2.0  120.0   NaN  106000
2       4.0  130.0   NaN  178100
3       NaN    NaN   NaN  140000


In [56]:
missing_values = data.isnull().sum()
print(missing_values)

column_with_max_missing = missing_values.idxmax()
print(column_with_max_missing)

data = data.drop(columns = [column_with_max_missing])
print(data)

NumRooms    2
Size        1
Alley       3
Price       0
dtype: int64
Alley
   NumRooms   Size   Price
0       NaN  100.0  127500
1       2.0  120.0  106000
2       4.0  130.0  178100
3       NaN    NaN  140000


In [58]:
X = torch.Tensor(data.to_numpy(dtype = float))
print(X)

tensor([[       nan, 1.0000e+02, 1.2750e+05],
        [2.0000e+00, 1.2000e+02, 1.0600e+05],
        [4.0000e+00, 1.3000e+02, 1.7810e+05],
        [       nan,        nan, 1.4000e+05]])


简要地回顾一下部分基本线性代数内容。
标量，仅半酣一个数值被称为标量 scalar。
变量 variable，表示未知的标量值。
标量由只有一个元素的张量表示。

In [59]:
x=torch.tensor(3.0)
y=torch.tensor(2.0)

x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

向量
向量可以被视为标量值组成的列表。这些标量被称为向量的元素element或者分量 component。
当向量表示数据中的样本时，它们的值具有一定的现实意义。
在数学表示法中，向量通常记为粗体、小写的符号。
人们通过一维张量表示向量，一般来说，向量可以具有任意长度，取决于机器的内存限制。

In [60]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

可以使用下标来引用向量的任一元素，例如可以通过xi来引用第i个元素。
大量文献认为列向量是向量的默认方向。

In [61]:
x[3]

tensor(3)

长度、维度和形状
向量只是一个数字数组，就像每个数组都有一个长度一样，每个向量也是如此。
向量的长度通常称为向量的维度demension。
与普通的python数组一样，可以通过调用python的内置len函数来访问张量的长度。

In [62]:
len(x)

4

矩阵
正如向量将标量从零阶推广到一阶，矩阵将向量从一阶推广到二阶。
矩阵，我们通常用粗体、大写字母来表示，在代码中表示为具有两个轴的张量。
矩阵A (m,n)或者m*n.
当矩阵具有相同数量的行和列时，其形状将变为正方形；因此被称为方阵 square matrix。
当调用函数来实例化张量时，我们可以通过指定两个分量m和n来创建一个形状为m*n的矩阵。


In [ ]:
A=torch.arange(20).reshape(5,4)
# A=torch.arange(20).reshape(5,-1)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

可以通过行索引和列索引来访问矩阵中的标量元素。
如果没有给出矩阵A的标量元素，可以简单地使用矩阵A地小写字母索引下标来引用。
当交换矩阵地行和列时，结果称为矩阵地转置transpose。

In [64]:
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


作为方阵地一种特殊类型，对称矩阵symmetric matrix等于其置换。

In [ ]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
print(B.T)
print(B==B.T)