In [2]:
import torch

张量表示一个由数值组成的数组，这个数组可能有多个维度。
具有一个轴的张量对应数学上的向量 vector； 具有两个轴的张量对应数学上的矩阵 matrix； 具有两个轴以上的张量没有特殊的数学名称。
张量中的每个值称为张量的元素 element

In [3]:
x = torch.arange(12)
print(x)
print(x.type()) # x的数据类型
print(x.shape) # x的形状
print(x.numel()) # x中元素的总数

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.LongTensor
torch.Size([12])
12


改变张量的形状而不改变元素数量和元素值，可以调用reshape函数。
通过改变张量的形状，张量的大小不会改变。

不需要通过手动指定每个维度来改变形状。如果目标形状是（高度，宽度），那么在知道宽度后，高度会被自动计算得出，不必自己做除法。
可以通过-1来调用自动计算维度的功能。

In [6]:
X = x.reshape(3,4)
print(X)

X = x.reshape(-1,4)
print(X)

X = x.reshape(3,-1)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


使用全0，全1，其他常量。

In [9]:
x = torch.zeros((2,3,4))
print(x)
y = torch.ones((2,3,4))
print(y)
z = torch.randn((2,3,4))
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[ 2.1304, -1.2695,  0.8879, -0.9276],
         [-0.6840, -0.2777,  1.4807,  0.6891],
         [ 0.7652, -0.7412,  1.6432,  0.0110]],

        [[ 0.1229,  1.0039, -0.0227,  0.4848],
         [-0.1732, -0.2292, -0.2549,  1.4869],
         [-0.0296, -0.1151, -1.3791,  1.2926]]])


运算符，按元素 elementwise运算。将标准标量运算符应用于数组的每个元素。对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每对位置对应的元素。
一元标量运算符：只接收一个输入
二元标量运算符：该函数接收两个输入，并产生一个输出。
给定同一形状的任意两个向量u和v和二元运算符f，我们可以得到向量C=F(u,v)。 具体的计算方法是Ci = f(ui,vi), Ci ui vi 分别是向量C,u,v中的元素。
在这里，我们通过将标量函数升级为按元素向量运算来生成向量值F: R, R->R

In [10]:
x = torch.Tensor([1.0,2,4,8])
y = torch.Tensor([2,2,2,2])

x+y, x-y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式可以应用更多的计算，包括像求幂的一元运算符。

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

可以将多个张量连结 concatenate在一起，端对端地叠起来形成一个更大的张量。
需要提供张量列表，并给出沿哪个轴连结。

In [15]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
print(X)

Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(Y)

torch.cat((X,Y), dim = 0), torch.cat((X,Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

逻辑运算符构建二元张量

In [16]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和，会产生一个单元素张量。

In [17]:
X.sum()

tensor(66.)

广播机制
在某些情况下，即使形状不同，仍然可以通过调用广播机制 broadcasting mechanism来执行按元素操作。
这种机制的工作方式如下：
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
2. 对生成的数组执行按元素操作

In [22]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)

c = a+b
print(c)
print(c.shape)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
torch.Size([3, 2])


索引和切片
张量中的元素可以通过索引访问。
与任何python数组一样：
第一个元素的索引是0，最后一个元素索引是-1，可以指定范围以包含第一个元素和最后一个之前的元素。

In [23]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，还可以通过指定索引来将元素写入矩阵。

In [24]:
print(X)
X[1,2] = 9

print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


如果要为多个元素赋值相同的值，只需要索引这些元素，然后为它们赋值。

In [25]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

节省内存
运行一些操作可能会导致为新结果分配内存。
例如如果用Y = X+Y, 将取消引用Y指向的向量，二十指向新分配的内存处的张量。
下面的例子中，用python的id()函数演示了这一点，它给我们提供了内存中引用对象的确切地址。

In [27]:
before = id(Y)
print(before)
Y = X+Y
id(Y) == before

3168816327152


False

这是不可取的，原因有两个：
1. 首先，我们不想总是不必要地分配内存。
2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

执行原地操作，可以使用切片表示法将操作的结果分配给先前分配的数组。

In [28]:
Z = torch.zeros_like(Y)
print(Z)
print('id(Z):', id(Z))

Z[:] = Z + Y
print(Z)
print('id(Z):', id(Z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 3168812976544
tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])
id(Z): 3168812976544


转换为其他python对象
将深度学习框架定义的张量转换为numpy张量narray很容易，反之亦然。
torch张量和numpy数组将共享它们的底层内存，就地操作更改一张张量也会同时更改另一个张量。

In [29]:
A = X.numpy()
B = torch.Tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为python标量，我们可以调用item函数或者python的内置函数

In [31]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)